import os
import json
import sys
import re
from state import GraphState
from observability import trace_node, trace_tool, log_decision

# Add Data_Dictionary to path
if os.path.join(os.getcwd(), 'Data_Dictionary') not in sys.path:
    sys.path.append(os.path.join(os.getcwd(), 'Data_Dictionary'))
from gemini_client import call_gemini

"""
### Concept: The Autonomous Orchestrator
The Orchestrator's role is to call other agents to perform an action based on user's input or the output generated by other agents.
It acts as the central brain that decides the workflow dynamically.
"""

class OrchestratorAgent:
    """
    The Autonomous Orchestrator (Brain) of the HyTE Engine.
    It uses LLM-based reasoning to decide the next step based on the current state.
    """
    
    def __init__(self):
        self.agents = {
            "methodology_agent": "Designs analysis strategy and identifies KPIs. Use for planning (Stage 1) and data-aware methodology (Stage 2).",
            "rag_agent": "Retrieves table schemas and metadata context. Use to ground the analysis in actual data after KPIs are identified.",
            "pseudocoding_agent": "Generates technical logic (pseudocode) for data processing for specific KPIs.",
            "code_generation_agent": "Generates Python code from approved pseudocode.",
            "code_execution_agent": "Executes Python scripts and saves results."
        }

    @trace_tool("Orchestrator Decision")
    def _get_autonomous_decision(self, state: GraphState):
        """Uses Gemini to decide the next action and update the plan."""
        
        messages = state.get("messages", [])
        last_message = messages[-1]["content"] if messages else ""
        current_step = state.get("current_step", "start")
        hypothesis = state.get("hypothesis", "")
        kpi_list = state.get("kpi_list", [])
        current_kpi = state.get("current_kpi", "")
        current_kpi_index = state.get("current_kpi_index", 0)
        current_plan = state.get("plan", [])
        
        context = {
            "current_step": current_step,
            "hypothesis": hypothesis,
            "has_strategy": bool(state.get("methodology") or state.get("initial_strategy")),
            "has_metadata": bool(state.get("metadata_context")),
            "kpi_list": kpi_list,
            "current_kpi": current_kpi,
            "current_kpi_index": current_kpi_index,
            "has_pseudocode": bool(state.get("pseudocode")),
            "has_python_code": bool(state.get("python_code")),
            "has_results": bool(state.get("kpi_execution_results")),
            "current_plan": current_plan
        }

        agent_descriptions = "\n".join([f"- {name}: {desc}" for name, desc in self.agents.items()])
        
        prompt = f"""
        You are the HyTE (Hypothesis Testing Engine) Deep Orchestrator. 
        Your job is to manage the hypothesis testing lifecycle using an autonomous plan.
        
        Available Agents:
        {agent_descriptions}
        
        Current System Context:
        {json.dumps(context, indent=2)}
        
        Last Input:
        "{last_message}"
        
        Your Task:
        1. Maintain and Update the Plan: If no plan exists, create one with 5-7 major milestones.
           Update the status of existing tasks (e.g., mark as 'completed', 'in_progress', or 'pending').
        2. Decide the Next Action: Based on the plan and current step, decide which agent to call.
        
        Valid Action Steps:
        - trigger_initial_strategy, refine_strategy (methodology_agent)
        - trigger_rag (rag_agent)
        - trigger_final_methodology, refine_methodology (methodology_agent)
        - trigger_pseudocode, refine_pseudocode (pseudocoding_agent)
        - trigger_codegen, refine_codegen (code_generation_agent)
        - trigger_execution (code_execution_agent)
        - strategy_generated, methodology_generated, pseudocode_generated, code_generated, executed (wait for user)
        
        Note: pseudocode and code generation now process ALL KPIs in one batch.
        Do NOT set current_kpi or current_kpi_index — the agents handle iteration internally.
        
        Return ONLY a JSON object:
        {{
            "next_step": "step_id",
            "action": "call_agent" | "respond_to_user",
            "agent": "agent_name" | null,
            "plan_update": [
                {{"task": "Task Name", "status": "pending"|"in_progress"|"completed", "notes": "brief update"}}
            ],
            "updates": {{
                "current_kpi": "...",
                "current_kpi_index": 0
            }},
            "message_to_user": "Concise summary of progress and plan update."
        }}
        """
        
        try:
            res_text = call_gemini(prompt).strip()
            res_text = re.sub(r'```json\s*|\s*```', '', res_text)
            decision = json.loads(res_text)
            return decision
        except Exception:
            return {
                "action": "respond_to_user",
                "next_step": current_step,
                "message_to_user": "I'm updating the analysis plan. One moment."
            }

    @trace_node("Orchestrator")
    def run(self, state: GraphState):
        """Processes the state and generates the orchestrator's decision."""
        current_step = state.get("current_step", "start")
        is_user_turn = state["messages"][-1]["role"] == "user" if state.get("messages") else False
        last_message = state["messages"][-1]["content"].strip().lower() if state.get("messages") else ""
        is_approval = last_message in ["approve", "yes", "proceed", "ok", "go ahead", "continue"]
        
        # 1. Start check
        if not state.get("hypothesis") and current_step == "start":
            return {
                "messages": [{"role": "assistant", "content": "Welcome to **HyTE Deep Agent**! Please share your hypothesis to begin."}],
                "current_step": "start"
            }

        # 2. Deterministic First Action: Hypothesis provided, no methodology exists
        #    Skip the LLM decision and go straight to strategy generation.
        has_methodology = bool(state.get("methodology") or state.get("initial_strategy"))
        is_first_run = current_step == "start"
        
        if state.get("hypothesis") and not has_methodology and is_first_run:
            # Capture hypothesis from user message if not already set
            hypothesis = state.get("hypothesis", "")
            if not hypothesis and state.get("messages"):
                hypothesis = state["messages"][-1].get("content", "")
            
            log_decision("Orchestrator", "trigger_hypothesis_refinement", {
                "reason": "Hypothesis provided, triggered refinement",
                "hypothesis": hypothesis
            })
            
            return {
                "hypothesis": hypothesis,
                "current_step": "trigger_hypothesis_refinement",
                "messages": [{"role": "assistant", "content": f"**Hypothesis received.** Let's refine it together to ensure high-quality analysis results..."}],
                "plan": [
                    {"task": "0. Refine Hypothesis", "status": "in_progress", "notes": "Ensuring the hypothesis is clear, specific, and testable."},
                    {"task": "1. Generate Initial Strategy", "status": "pending", "notes": "Designing data-agnostic approach, assumptions, KPIs, and visualizations."},
                    {"task": "2. RAG Data Discovery", "status": "pending", "notes": "Retrieve relevant tables from Knowledge Graph."},
                    {"task": "3. Data-Aware Methodology", "status": "pending", "notes": "Refine strategy with actual data context."},
                    {"task": "4. Per-KPI Pseudocode", "status": "pending", "notes": "Generate logic for each KPI."},
                    {"task": "5. Code Generation", "status": "pending", "notes": "Convert pseudocode to Python."},
                    {"task": "6. Execution & Merge", "status": "pending", "notes": "Run scripts and merge datasets."}
                ]
            }
        
        # 2c. Handle Hypothesis Refinement feedback
        if current_step == "hypothesis_refinement" and is_user_turn:
            return {
                "current_step": "trigger_hypothesis_refinement",
                "latest_feedback": state["messages"][-1]["content"],
                "messages": [{"role": "assistant", "content": "Processing your clarification..."}]
            }


        # 2b. Deterministic Post-Methodology Flow: Handle approvals at strategy/methodology/pseudocode/code review
        #     These don't need LLM decisions — they follow a fixed pipeline.
        
        if is_user_turn and current_step == "strategy_generated":
            if is_approval:
                log_decision("Orchestrator", "trigger_rag", {
                    "reason": "User approved strategy, triggering RAG data discovery"
                })
                return {
                    "current_step": "trigger_rag",
                    "messages": [{"role": "assistant", "content": "**Strategy approved.** Retrieving relevant data tables and metadata context..."}],
                    "plan": [
                        {"task": "0. Refine Hypothesis", "status": "completed", "notes": "Hypothesis finalized."},
                        {"task": "1. Generate Initial Strategy", "status": "completed", "notes": "Strategy approved by user."},
                        {"task": "2. RAG Data Discovery", "status": "in_progress", "notes": "Retrieving schemas from Knowledge Graph."},
                        {"task": "3. Data-Aware Methodology", "status": "pending", "notes": "Refine strategy with actual data context."},
                        {"task": "4. Per-KPI Pseudocode", "status": "pending", "notes": "Generate logic for each KPI."},
                        {"task": "5. Code Generation", "status": "pending", "notes": "Convert pseudocode to Python."},
                        {"task": "6. Execution & Merge", "status": "pending", "notes": "Run scripts and merge datasets."}
                    ]
                }
            else:
                # User gave feedback — route to refine_strategy
                log_decision("Orchestrator", "refine_strategy", {
                    "reason": "User provided strategy feedback",
                    "feedback": last_message
                })
                return {
                    "current_step": "refine_strategy",
                    "latest_feedback": state["messages"][-1]["content"],
                    "messages": [{"role": "assistant", "content": "Refining initial strategy based on your feedback..."}]
                }

        # 2d. Deterministic RAG to Methodology transition
        if current_step == "rag_generated":
            log_decision("Orchestrator", "trigger_final_methodology", {
                "reason": "RAG data discovery complete, triggering final data-aware methodology"
            })
            return {
                "current_step": "trigger_final_methodology",
                "messages": [{"role": "assistant", "content": "**Data tables retrieved.** Now refining the strategy into a detailed, data-aware methodology..."}],
                "plan": [
                    {"task": "2. RAG Data Discovery", "status": "completed", "notes": "Schemas retrieved."},
                    {"task": "3. Data-Aware Methodology", "status": "in_progress", "notes": "Refining strategy with metadata."},
                    {"task": "4. Per-KPI Pseudocode", "status": "pending", "notes": "Generate logic for each KPI."},
                    {"task": "5. Code Generation", "status": "pending", "notes": "Convert pseudocode to Python."},
                    {"task": "6. Execution & Merge", "status": "pending", "notes": "Run scripts and merge datasets."}
                ]
            }

        if is_user_turn and current_step == "methodology_generated":
            if is_approval:
                log_decision("Orchestrator", "trigger_pseudocode", {
                    "reason": "User approved methodology, triggering batch pseudocode generation"
                })
                return {
                    "current_step": "trigger_pseudocode",
                    "messages": [{"role": "assistant", "content": "**Methodology approved.** Generating pseudocode for all KPIs..."}],
                    "plan": [
                        {"task": "3. Data-Aware Methodology", "status": "completed", "notes": "Methodology approved by user."},
                        {"task": "4. Per-KPI Pseudocode", "status": "in_progress", "notes": "Generating pseudocode for all KPIs."},
                        {"task": "5. Code Generation", "status": "pending", "notes": "Convert pseudocode to Python."},
                        {"task": "6. Execution & Merge", "status": "pending", "notes": "Run scripts and merge datasets."}
                    ]
                }
            else:
                # User gave feedback — route to refine_methodology
                log_decision("Orchestrator", "refine_methodology", {
                    "reason": "User provided methodology feedback",
                    "feedback": last_message
                })
                return {
                    "current_step": "refine_methodology",
                    "latest_feedback": state["messages"][-1]["content"],
                    "messages": [{"role": "assistant", "content": "Refining methodology based on your feedback..."}]
                }
        
        if is_user_turn and current_step == "pseudocode_generated":
            if is_approval:
                log_decision("Orchestrator", "trigger_codegen", {
                    "reason": "User approved pseudocode for all KPIs, proceeding to code generation"
                })
                return {
                    "current_step": "trigger_codegen",
                    "messages": [{"role": "assistant", "content": "**Pseudocode approved.** Generating Python code for all KPIs..."}],
                    "plan": [
                        {"task": "4. Per-KPI Pseudocode", "status": "completed", "notes": "All KPI pseudocode approved."},
                        {"task": "5. Code Generation", "status": "in_progress", "notes": "Generating Python code for all KPIs."},
                        {"task": "6. Execution & Merge", "status": "pending", "notes": "Run scripts and merge datasets."}
                    ]
                }
            else:
                # User gave feedback — route to refine_pseudocode with selective refinement
                log_decision("Orchestrator", "refine_pseudocode", {
                    "reason": "User provided feedback on pseudocode",
                    "feedback": last_message
                })
                return {
                    "current_step": "refine_pseudocode",
                    "latest_feedback": state["messages"][-1]["content"],
                    "messages": [{"role": "assistant", "content": "Refining pseudocode based on your feedback..."}]
                }
        
        if is_user_turn and current_step == "code_generated":
            if is_approval:
                log_decision("Orchestrator", "trigger_execution", {
                    "reason": "User approved code for all KPIs, proceeding to execution"
                })
                return {
                    "current_step": "trigger_execution",
                    "messages": [{"role": "assistant", "content": "**Code approved.** Executing all KPI scripts against the datalake..."}],
                    "plan": [
                        {"task": "5. Code Generation", "status": "completed", "notes": "All KPI code approved."},
                        {"task": "6. Execution & Merge", "status": "in_progress", "notes": "Running all KPI scripts."}
                    ]
                }
            else:
                # User gave feedback — route to refine_codegen with selective refinement
                log_decision("Orchestrator", "refine_codegen", {
                    "reason": "User provided feedback on code",
                    "feedback": last_message
                })
                return {
                    "current_step": "refine_codegen",
                    "latest_feedback": state["messages"][-1]["content"],
                    "messages": [{"role": "assistant", "content": "Refining code based on your feedback..."}]
                }

        # 3. Get Autonomous Decision (LLM-based for all subsequent steps)
        decision = self._get_autonomous_decision(state)
        
        next_step = decision.get("next_step", state.get("current_step"))
        message = decision.get("message_to_user", "")
        decision_updates = decision.get("updates", {})
        plan_update = decision.get("plan_update")
        
        log_decision("Orchestrator", next_step, {
            "from_step": state.get("current_step"),
            "agent": decision.get("agent"),
            "message": message
        })
        
        updates = {
            "current_step": next_step
        }
        
        if plan_update:
            updates["plan"] = plan_update

        # Apply any state updates from the LLM
        if isinstance(decision_updates, dict):
            for k, v in decision_updates.items():
                if v is not None:
                    updates[k] = v

        # 3. Capture Initial Hypothesis
        is_user_turn = state["messages"][-1]["role"] == "user" if state.get("messages") else False
        if is_user_turn and not state.get("hypothesis"):
             updates["hypothesis"] = state["messages"][-1]["content"]

        # 4. Handle Feedback
        if is_user_turn and ("refine" in next_step or next_step == state.get("current_step")):
            updates["latest_feedback"] = state["messages"][-1]["content"]

        # 5. Messaging with Plan Summary
        if message:
            plan_str = ""
            if plan_update:
                plan_str = "\n\n### 📝 Active Plan\n"
                for task in plan_update:
                    status_icon = "✅" if task["status"] == "completed" else "⏳" if task["status"] == "in_progress" else "⚪"
                    plan_str += f"- {status_icon} **{task['task']}**: {task['notes']}\n"
            
            updates["messages"] = [{"role": "assistant", "content": f"{message}{plan_str}"}]
            
        return updates
